#!/usr/bin/env bash

aptitude install \
ansible \
docker.io \
git \
jq \
nodejs \
nodejs-dev \
npm \
python \
python-pip \
ruby \
ruby-dev \
virtualbox \
vagrant

pip install awscli boto
gem install aws-sdk-core
npm install grunt-cli

echo "!!!! http://downloads.getchef.com/chef-dk/ !!!!"

