#!/usr/bin/env bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install \
aggregate \
ansible \
apg \
autossh \
awscli \
bash-completion \
cksfv \
cmake \
dos2unix \
fdupes \
ipcalc \
htop \
imagemagick \
ipcalc \
mosh \
mtr \
ncftp \
netcat \
ngrep \
nmap \
node \
python \
pygtk \
ruby \
tcptraceroute \
tmux \
vte \
watch

brew install homebrew/dupes/openssh
brew install libgit2 --with-libssh2
brew install Caskroom/cask/keepassx
npm install -g grunt-cli
